### ISSUE TITLE
I need help! Could not load dynamic library 'libnvinfer.so.6' and  'libnvinfer_plugin.so.6'

### ISSUE THREAD

**Issue by voyager0003** [microsoft/DisentangledFaceGAN#20]
Thanks for sharing the training code! the result of DiscoFace GAN is awesome!

However, when I test the project following the readme, An error occured:

2021-02-03 12:23:02.634079: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/opt/conda/lib
2021-02-03 12:23:02.634189: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/opt/conda/lib
2021-02-03 12:23:02.634202: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use **Nvidia GPU with TensorRT**, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "generate_images.py", line 10, in <module>
    from training import misc
  File "/ml_workspace/caishuxiao/DiscoFaceGAN-master/training/misc.py", line 20, in <module>
    from training import dataset
  File "/ml_workspace/caishuxiao/DiscoFaceGAN-master/training/dataset.py", line 15, in <module>
    import dnnlib.tflib as tflib
  File "/ml_workspace/caishuxiao/DiscoFaceGAN-master/dnnlib/tflib/__init__.py", line 8, in <module>
    from . import autosummary
  File "/ml_workspace/caishuxiao/DiscoFaceGAN-master/dnnlib/tflib/autosummary.py", line 31, in <module>
    from . import tfutil
  File "/ml_workspace/caishuxiao/DiscoFaceGAN-master/dnnlib/tflib/tfutil.py", line 34, in <module>
    def shape_to_list(shape: Iterable[tf.Dimension]) -> List[Union[int, None]]:
AttributeError: module 'tensorflow' has no attribute 'Dimension'

So which TensorRT version should I install? Or How to fix "'tensorflow' has no attribute 'Dimension'"

**Comment by voyager0003** [comment]
a bug caused by conda environment cache 
conda deactivate 
conda activate xxxx
